# Generated by Django 2.2.7 on 2019-12-19 08:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCSPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point_name', models.CharField(blank=True, default='', help_text='测点名称', max_length=30, verbose_name='测点名称')),
                ('point_code', models.CharField(blank=True, default='', help_text='测点位号', max_length=30, verbose_name='测点位号')),
                ('point_desc', models.TextField(blank=True, default='', help_text='测点描述', verbose_name='测点描述')),
                ('point_connection_status', models.BooleanField(blank=True, default=False, help_text='测点连接状况', verbose_name='测点连接状况')),
                ('point_add_to_service', models.BooleanField(blank=True, default=False, help_text='测点添加到界面', verbose_name='测点添加到界面')),
                ('point_H_limitation', models.FloatField(blank=True, default=0, help_text='测点上限', verbose_name='测点上限')),
                ('point_L_limitation', models.FloatField(blank=True, default=0, help_text='测点下限', verbose_name='测点下限')),
                ('point_HH_limitation', models.FloatField(blank=True, default=0, help_text='测点上上限', verbose_name='测点上上限')),
                ('point_LL_limitation', models.FloatField(blank=True, default=0, help_text='测点下下限', verbose_name='测点下下限')),
                ('point_realtime_value', models.FloatField(blank=True, default=0, help_text='测点当前值', verbose_name='测点当前值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('DCS_point_category', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'DCS测点属性',
                'verbose_name_plural': 'DCS测点属性',
                'db_table': 'SCMS_DCS_Point_Reference',
            },
        ),
        migrations.CreateModel(
            name='DCSPointCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, default='', help_text='分类名', max_length=30, verbose_name='分类名')),
                ('category_code', models.CharField(blank=True, default='', help_text='分类code', max_length=30, verbose_name='分类code')),
                ('category_desc', models.TextField(blank=True, default='', help_text='分类描述', verbose_name='分类描述')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('DCS_category_type', models.IntegerField(choices=[(1, 'DCS一级类别'), (2, 'DCS二级类别'), (3, 'DCS三级类别'), (4, 'DCS四级类别')], help_text='DCS类别分类', verbose_name='DCS类别分类')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='DCS_Point_Interface.DCSPointCategory', verbose_name='父类目级')),
            ],
            options={
                'verbose_name': 'DCS测点分类',
                'verbose_name_plural': 'DCS测点分类',
                'db_table': 'SCMS_DCS_Category',
            },
        ),
    ]
