# Generated by Django 2.2.7 on 2019-12-19 23:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SISFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('flag_1', models.BooleanField(blank=True, default=False, null=True)),
                ('flag_2', models.BooleanField(blank=True, default=False, null=True)),
                ('flag_3', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'SIS点实时报警',
                'verbose_name_plural': 'SIS点实时报警',
                'db_table': 'SMCS_SIS_Flag',
            },
        ),
        migrations.CreateModel(
            name='SISPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point_name', models.CharField(blank=True, default='', help_text='测点名称', max_length=30, verbose_name='测点名称')),
                ('point_code', models.CharField(blank=True, default='', help_text='测点位号', max_length=30, verbose_name='测点位号')),
                ('point_desc', models.TextField(blank=True, default='', help_text='测点描述', verbose_name='测点描述')),
                ('point_connection_status', models.BooleanField(blank=True, default=False, help_text='测点连接状况', verbose_name='测点连接状况')),
                ('point_add_to_service', models.BooleanField(blank=True, default=False, help_text='测点添加到界面', verbose_name='测点添加到界面')),
                ('point_H_limitation', models.FloatField(blank=True, default=0, help_text='测点上限', verbose_name='测点上限')),
                ('point_L_limitation', models.FloatField(blank=True, default=0, help_text='测点下限', verbose_name='测点下限')),
                ('point_HH_limitation', models.FloatField(blank=True, default=0, help_text='测点上上限', verbose_name='测点上上限')),
                ('point_LL_limitation', models.FloatField(blank=True, default=0, help_text='测点下下限', verbose_name='测点下下限')),
                ('point_realtime_value', models.FloatField(blank=True, default=0, help_text='测点当前值', verbose_name='测点当前值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('is_tab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SIS测点属性表',
                'verbose_name_plural': 'SIS测点属性表',
                'db_table': 'SCMS_SIS_Point_Reference',
            },
        ),
        migrations.CreateModel(
            name='SISPointOnMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SIS_point_code', models.CharField(max_length=30)),
                ('DCS_point_code', models.CharField(max_length=30)),
                ('correlation_weight', models.FloatField()),
            ],
            options={
                'verbose_name': 'SIS目标点的特征映射',
                'verbose_name_plural': 'SIS目标点的特征映射',
                'db_table': 'SCMS_SIS_DP_FE_ML',
            },
        ),
        migrations.CreateModel(
            name='SISRealtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('point_1', models.FloatField(blank=True, default=0, help_text='测点当前值', null=True, verbose_name='测点当前值')),
                ('point_2', models.FloatField(blank=True, default=0, help_text='测点当前值', null=True, verbose_name='测点当前值')),
                ('point_3', models.FloatField(blank=True, default=0, help_text='测点当前值', null=True, verbose_name='测点当前值')),
            ],
            options={
                'verbose_name': 'SIS点实时数据',
                'verbose_name_plural': 'SIS点实时数据',
                'db_table': 'SMCS_SIS_REALTIME',
            },
        ),
        migrations.CreateModel(
            name='SISPointCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, default='', help_text='分类名', max_length=30, verbose_name='分类名')),
                ('category_code', models.CharField(blank=True, default='', help_text='分类code', max_length=30, verbose_name='分类code')),
                ('category_desc', models.TextField(blank=True, default='', help_text='分类描述', verbose_name='分类描述')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('SIS_category_type', models.IntegerField(choices=[(1, 'SIS一级类别'), (2, 'SIS二级类别'), (3, 'SIS三级类别'), (4, 'SIS四级类别')], help_text='SIS类别分类', verbose_name='SIS类别分类')),
                ('is_tab', models.BooleanField(default=False)),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='SIS_Point_Interface.SISPointCategory', verbose_name='父类目级')),
            ],
            options={
                'verbose_name': 'SIS测点分类',
                'verbose_name_plural': 'SIS测点分类',
                'db_table': 'SCMS_SIS_Category',
            },
        ),
    ]
