# Generated by Django 2.2.7 on 2019-12-20 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_Point_Interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sisflag',
            old_name='flag_1',
            new_name='arsa_41301_flag',
        ),
        migrations.RenameField(
            model_name='sisflag',
            old_name='flag_2',
            new_name='pisa_4204_flag',
        ),
        migrations.RenameField(
            model_name='sisflag',
            old_name='flag_3',
            new_name='prcsa_4201_flag',
        ),
        migrations.RenameField(
            model_name='sisrealtime',
            old_name='point_1',
            new_name='arsa_41301',
        ),
        migrations.RenameField(
            model_name='sisrealtime',
            old_name='point_2',
            new_name='pisa_4204',
        ),
        migrations.RenameField(
            model_name='sisrealtime',
            old_name='point_3',
            new_name='prcsa_4201',
        ),
    ]
